### ISSUE TITLE
Visual glitch with origins mod

### ISSUE THREAD

**Issue by ChloeIsNobody** [RebelKeithy/ExtendedArmorBars#1]
if the origins mod is installed, all resource/cooldown bars from the mod will render over the armor toughness bar, covering it almost completely

**Comment by RebelKeithy** [comment]
I'm not sure how to dynamically adjust to their resource bars, but I can add a configurable y offset to my bars.

**Comment by RebelKeithy** [comment]
Version 1.1 has an option to offset the armor/toughness bars.
